PRAGMA FOREIGN_KEYS = ON;

DROP TABLE visits;
DROP TABLE travelers;
DROP TABLE locations;

CREATE TABLE travelers (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name VARCHAR
);

CREATE TABLE locations (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  category VARCHAR,
  name VARCHAR
);


CREATE TABLE visits (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  traveler_id INTEGER NOT NULL,
  location_id INTEGER NOT NULL,
  review TEXT,
    FOREIGN KEY (traveler_id)
      REFERENCES travelers(id) ON DELETE CASCADE,
    FOREIGN KEY (location_id)
      REFERENCES locations(id) ON DELETE CASCADE
);